name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger Render Deployment
        env:
          RENDER_API_KEY: ${rnd_ypLTEgLLMiz7Twg7lCg2kEEVDlvr}
          RENDER_SERVICE_ID: ${rnd_9f8d3b2c-1234-5678-90ab-cdef12345678}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"serviceId\":\"${RENDER_SERVICE_ID}\"}" \
            https://api.render.com/v1/deploys
